<h2 style='color:pink'> Data Gathering :</h2>

- <h3 style='color:red'>Working with CSV</h3>
- <h3 style='color:red'>Working wih JSON/SQL</h3>
- <h3 style='color:red'>Fetching API</h3>
- <h3 style='color:red'>Web Scraping</h3>

<h3 style='color:pink'> 1. Working with CSV</h3>

In [6]:
import pandas as pd

C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\placement.csv

In [2]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\placement.csv')

<h3 style='color:pink'> 2. Opening csv file from URL</h3>

In [ ]:
# code snippet used for opening file
import requests
from io import StringIO

url = 'url'
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

<h3 style='color:pink'> 3. Sep Parameter</h3>

- In read_csv fn used for opening comma separated val, the value of sep is ',' but In tsv where all val is separated by 'tab'.
- So sep value for tsv file is 'tab', so we need to override this value as 'tab'
- Also pass name list as first row become label row.

In [2]:
# pd.read_csv(r'', sep='\t', names=[])

<h3 style='color:pink'> 4. Index col parameter</h3>

In [9]:
# in this index_col attribute, write that col which we need to treat as s.no
pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\db.csv', index_col='S.no')

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
S.no,,,,,,,,,,
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

<h3 style='color:pink'> 5. Header Para</h3>
- when header col is treated as first row by read fn, then we manually assign header using it

In [ ]:
pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\db.csv', header=1)

,0,0.038075906433423026,0.05068011873981862,0.061696206518683294,0.0218723855140367,-0.04422349842444599,-0.03482076283769895,-0.04340084565202491,-0.002592261998183278,0.019907486170462722,-0.01764612515980379
0,1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
1,2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
2,3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
3,4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
4,5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
...,...,...,...,...,...,...,...,...,...,...,...
436,437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
437,438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
438,439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
439,440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
440,441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

<h3 style='color:pink'> 6. use_col Parameter</h3>
- When we need only selected col from whole dataset

In [11]:
pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\db.csv', usecols=['age','sex','bmi','bp'])

          age       sex       bmi        bp
0    0.038076  0.050680  0.061696  0.021872
1   -0.001882 -0.044642 -0.051474 -0.026328
2    0.085299  0.050680  0.044451 -0.005670
3   -0.089063 -0.044642 -0.011595 -0.036656
4    0.005383 -0.044642 -0.036385  0.021872
..        ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744
438 -0.005515  0.050680 -0.015906 -0.067642
439  0.041708  0.050680 -0.015906  0.017293
440 -0.045472 -0.044642  0.039062  0.001215
441 -0.045472 -0.044642 -0.073030 -0.081413

[442 rows x 4 columns]

<h3 style='color:pink'> 7. Skiprows/nrows Para</h3>

- Skiprows allows to Skip rows which we want
- nrows allows to select a specific no of rows from dataset

In [18]:
pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\db.csv', skiprows=lambda x : x == 5)

,S.no,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
...,...,...,...,...,...,...,...,...,...,...,...
436,437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
437,438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
438,439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
439,440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
440,441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

<h3 style='color:pink'> 8. Encoding Para</h3>

- Some csv files is encoded in some other way, so for encoding them we use it

In [19]:
# pd.read_csv(r'', encoding='latin-1')

<h3 style='color:pink'> 9. Skip bad lines</h3>

- When some lines values shows unexpexted values, so we skip those rows

In [20]:
# pd.read_csv(r'', encoding='latin-1', error_bad_lines=False)

<h3 style='color:pink'> 10. dtype Para</h3>

- Overriding datatype of a col

In [21]:
# pd.read_csv(r'', dtype={'target': int}).info()

<h3 style='color:pink'> 11. Handling Dates</h3>

- Changing dates datatype to date as in pd date is traeated as obj of string

In [22]:
# pd.read_csv(r'', parse_dates=['date']).info()

<h3 style='color:pink'> 12. Converters</h3>

- To convert big names to short forms
- For this, firt right a fn for it and then apply it in readcsv attribute

In [23]:
def rename(name):
    if name == 'Royal Challenger Banglore':
        return 'RCB'
    else:
        return name

In [24]:
# pd.read_csv(r'', converters={'team1':rename})

<h3 style='color:pink'> 13. Loading a huge dataset in chunks</h3>

In [28]:
dfs = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\db.csv', chunksize=100)

In [29]:
for chunks in dfs:
    print(chunks.size)

1100
1100
1100
1100
462