# PROJECT WORKFLOW:
- importing dependencies
- valcnt of imbalance value
- distriutn of transctn
- groupby class info
- under sampling
- concatenate samplr
- spliting into f and t
- spliting train & test
- model training
- evaluatn

In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\credit_data.csv')

In [3]:
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

- Info about dataset

In [5]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

- 0  --> Legit
- 1  --> Fraud

In [10]:
credit_card_data.describe()

                Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  1.175161e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

- distributing transctn

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
print(legit.shape, fraud.shape)

(284315, 31) (492, 31)

In [17]:
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

- Under sampling

In [18]:
legit_sample = legit.sample(n=500)

- Concatenate sample and fraud trans

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [20]:
new_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94982.528000 -0.054268 -0.248983  ... -0.005060  0.063566  124.918820
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

Here, mean data of both(creditcard & newData) is similar, So it's good sample dataset

- Separating feature and target

In [21]:
x = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [22]:
print(y)

25614     0
52706     0
149268    0
122032    0
62511     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 992, dtype: int64

- Splitting data into train & test

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [24]:
print(x.shape, x_train.shape, x_test.shape)

(992, 30) (793, 30) (199, 30)

- Model Training

In [25]:
model = LogisticRegression()

In [26]:
model.fit(x_train, y_train)

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

- Evaluation

In [29]:
x_train_pred = model.predict(x_train)
training_pred = accuracy_score(x_train_pred, y_train)

In [30]:
print(training_pred)

0.9445145018915511

In [31]:
x_test_pred = model.predict(x_test)
testing_pred = accuracy_score(x_test_pred, y_test)

In [32]:
print(testing_pred)

0.9346733668341709