# PCA(Principal Component Analysis)
- It is a Unsuperivsed learning problem
- It is a Feature Extraction Technique
- It's aim is to Reduce COD(Curse of Dimensionality)
- PCA Core aim is to capture the Essence of data from higher Dimension to Lowest possible Dimension
- So PCA transform a Higher dim data to a Lower dim data while keeping Essence or behaviour of data
> Benefits :
- FAster execution of algo
- Visualization(convert high dim to 2D/3D)

<h3># Geometric Intitution</h3>

1. Feature Selectn working:
- If we want to know which feature is important, plot it graphs and see whose projection / spread is more that's important
- But if projection of features is same and can't decide which is imp, then we use Feature Extratn
2. Feature Extratn Working
- It takes reference of existing features and make new featrs and choose subset from them which he thinks is most important
- So it shifts axis and forms new axis named as PC(Principal Component) which equal to previous in no's and selects imp one from them and transformed that data a/c to imp PC
- No of PC <= No of original features

> WHY Variance is IMP?
- Mean represents centre or avg of data
- Variance = (sigma(Xi - X')^2)/n
- Variance != Spread
- Variance is directly proportional to Spread
- So why MAD(Mean Abs Deviatn also represent spread) is not used in PCA
- Because Mod fn is not differentiable at 0, so when optimisatn algo's is used we'll not get answer

<img src='Screenshot 2026-02-28 193927.png'></img>

- As in this image, if we consider Spread and start comparing the spread of y is less and if we select it, that will be wrong judgement but if we consider variance we can take right axis 'x' as feature instead of 'y'

<img src='Screenshot 2026-02-28 202212.png'></img>

- So we will choose that unit vector whose Variance will be maximum
- By finding projection of vectors/data pts present in dataset on unit vector, we get scalar. So for every data pt we get a scalar

<img src='Screenshot 2026-02-28 202928.png'></img>

- Here we get Variance of all data pts projected on unit vectors and we need to maximize it, so for this we find that unit vector/quantity which maximize Variance.
- SO HERE, PCA FINDS THAT UNIT VECTOR FOR MODEL WHICH MAXIMIZE VARIANCE AND IMPROVE PERFOMANCE

<h3># Covariance and Covariance matrix</h3>

<img src='Screenshot 2026-02-28 210334.png'></img>

- Variance does not tells the realtion b/w to features and it's vals can be same
- SO Covariance is a method which tells about the relation b/w features

<img src='Screenshot 2026-02-28 210858.png'></img>

- So Covariance gives info about variance of all features or how data spread on axis as well as relation b.w features

<h3># Eigen Vectors and Values</h3>

- Matrices are linear transformatn when applied to coordinate system, transforms all pts or vectors

> Eigen Vectors
- These are the special vectors whose direction does not change(mag can change) when transformatn is applied
- Whenever we apply L.T, we get two Eigen vectors(2D) whose dir doesn't change
- Formula :  A.V^ = lmbda.V^
- Means when we aply L.T on a vector V^ is equal to multiplying that vector with scalar(eigen val) val

> Eigen Values
- The factor with which eigen vector transformed is called it's eigen values

> WHY Eigen Vectors and Values used in PCA?
- The largest eigen vector(of corresponding eigen vals) of the covariance matrix always points into the direction of largest variance of data.
- Means it helps in finding the unit vector which maximize variance
- So to finds maximum variance, Find the largest eigen vectors/vals of given covariance matrix

<h3># Solution Steps </h3>

<img src='Screenshot 2026-02-28 214005.png'></img>

1. Mean centric
2. Find Covariance matrix
3. Find eigen vectors and vals
4. It will give 2(2D) or 3(3D) vals and so choose 1 or 2 feature and largest one will be PC1

> How to transform?

<img src='Screenshot 2026-03-02 174257.png'></img>

- Do the dot product of data points with unit vector transpose

In [4]:
import numpy as np
import pandas as pd

np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['features1','features2','features3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['features1','features2','features3'])
df1['target'] = 0

df = pd.concat([df,df1], ignore_index=True)

df = df.sample(40)

In [5]:
df.head()

    features1  features2  features3  target
2   -0.367548  -1.137460  -1.322148       1
34   0.177061  -0.598109   1.226512       0
14   0.420623   0.411620  -0.071324       1
11   1.968435  -0.547788  -0.679418       1
12  -2.506230   0.146960   0.606195       1

In [6]:
import plotly.express as px
fig = px.scatter_3d(df, x=df['features1'], y=df['features2'], z=df['features3'], color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                    selector=dict(mode='markers'))

fig.show()

# Applying PCA

In [7]:
# Step 1 : Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [8]:
# Step 2 : Finding covariance matrix
covar_matrix = np.cov([df.iloc[:,0], df.iloc[:,1], df.iloc[:,2]])
print("Covariance Matrix:\n", covar_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]

In [9]:
# Step 3 : Finding Eigen Vector and Values
eigen_vals, eigen_vectors = np.linalg.eig(covar_matrix)

In [10]:
eigen_vals

array([1.3536065 , 0.94557084, 0.77774573])

In [11]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [13]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch

class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self.verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self.verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['features1'], df['features2'], df['features3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['features1'].mean()], [df['features2'].mean()], [df['features3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['features1'].mean(), v[0]], [df['features2'].mean(), v[1]], [df['features3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

In [14]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [15]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

        PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [16]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

<h3>Finding Optimum no of PCs</h3>
<img src='Screenshot 2026-03-02 203835.png'></img>

- Every eigen val tells how much its correspoding vector explain variance of original data
- Eigen vals or lambda tells how much this PC alone can explain variance of original data 
- We take PC or lbda till they can explain 90% of variance 
- pca.explained_variance_ratio_  = tells how much percentage it explains variance
- Plot the pca.explained_variance_ratio_ and see how much PCs give 90% and take that amount of PCs

- first do without pca
- then apply pca and compare the results
- visualise it
- then see how much PCs needed

<h3>When PCA does not work</h3>
<img src='Screenshot 2026-03-02 205256.png'></img>

- When data have specific pattern like sin curve, x^2 curve etc as all data will spread in a particular range